config/routes.rb
Rails.application.routes.draw do



  resources :groups
  resources :studentsgroups


  resources :disciplines, except: :show

  resources :teachers

  resources :students do
    resources :studentsdisciplines
    resources :studentsgroups
  end


end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  has_many :studentsdisciplines, dependent: :destroy
  has_many :students, through: :studentsdisciplines
  has_many :groups
  has_many :teachers, through: :groups

  KLASSES = [['1 kl.', 1], ['2 kl.', 2], ['3 kl.', 3], ['4 kl.', 4], ['5 kl.', 5], ['6 kl.', 6], ['7 kl.', 7], ['1 MMUP', 8], ['2 MMUP', 9], ['3 MMUP', 10], ['4 MMUP', 11]]
  SPECIALITIES = ['Fortepijonas', 'Akordeonas', 'Chorinis dainavimas', 'Styginiai', 'Pučiamieji']
  SYLLABUS = ['Pradinio ugdymo', 'Pagrindinio ugdymo']
  VARIANTS = ['Individuali pamoka', 'Grupinė pamoka']

  scope :find_by_klass, ->(kl) {where(klass: kl)}
  scope :find_by_speciality, ->(sp) { where(speciality: sp) }

  def is_required?
    self.required ? 'Taip' : 'Ne'
  end

  def what_status?
    self.status ? 'Aktyvus' : 'Neaktyvus'
  end

  def individual?
    self.variant == "Individuali pamoka"
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :discipline

  has_many :studentsgroups, dependent: :destroy
  has_many :students, through: :studentsgroups

  accepts_nested_attributes_for :students

  validates :name, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :studentsdisciplines, dependent: :destroy
  has_many :studentsgroups, dependent: :destroy
  has_many :disciplines, through: :studentsdisciplines
  has_many :groups, through: :studentsgroups

  accepts_nested_attributes_for :groups



  def initial_disciplines?
    klass <= 3
  end

  def main_disciplines?
    klass >= 4
  end

  def mmup?
    klass == 8
  end
end

app/models/studentsdiscipline.rb
class Studentsdiscipline < ActiveRecord::Base
  belongs_to :student
  belongs_to :discipline

  scope :active_only, -> { where(status_b: true) }
end

app/models/studentsgroup.rb
class Studentsgroup < ActiveRecord::Base
  belongs_to :student
  belongs_to :group
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :groups
  has_many :disciplines, through: :groups

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  def index
    @disciplines = Discipline.all
  end

  def edit
    @discipline = Discipline.find(params[:id])
  end

  def new
    @discipline = Discipline.new
  end

  def update
    @discipline = Discipline.find(params[:id])
    @discipline.update(discipline_params)
    redirect_to :disciplines
  end

  def create
    @discipline = Discipline.new(discipline_params)
    @discipline.save
    redirect_to :disciplines
  end

  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy
    redirect_to :disciplines
  end

private

  def discipline_params
    params.require(:discipline).permit(:name, :klass, :variant, :duration, :speciality, :syllabus, :required, :status)
  end

  def when_changed_status(discipline)
    discipline.students.each do |student|
      sd = student.disciplines
      if discipline.status
        sd << discipline unless sd.include?(discipline)
      else
        sd.delete(discipline)
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to :groups
  end

  def new
    @students = Student.all
    @group = Group.new
  end

  def create
    binding.pry
    @group = Group.new(group_params)
    @group.save


    redirect_to :groups
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to :groups
  end

private
  def group_params
    params.require(:group).permit(:name, :description, :teacher_id, :discipline_id, :variant, :students_attributes)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    var1 = @student.speciality
    @student.update(student_params)
    var2 = @student.speciality
    unless var1 == var2

    #   if @student.studentsdisciplines.any?
    #     a = @student.studentsdisciplines
    #     b = @student.disciplines
    #     v = b.where(speciality: @student.speciality)
    #     v.each do |d|
    #       a.where(discipline_id: d.id) { |n| n.update(status_b: true)}
    #     end

    #   else
    #     create_required_disciplines(@student)
    #   end
    # else
      @student.studentsdisciplines.each { |d| d.update(status_b: false)}
      create_required_disciplines(@student)
    end
    # var = @student.disciplines.find_by_speciality(@student.speciality)
    redirect_to @student
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.save
    create_required_disciplines(@student)
    redirect_to @student
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_url
  end

private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :klass, :speciality)
  end

  def create_required_disciplines(student)
    d = Discipline.find_by_klass(student.klass).find_by_speciality(student.speciality)
    d.each do |discipline|
      # unless discipline.in?(student.disciplines)
      student.disciplines << discipline if discipline.status
    end
  end
end

app/controllers/studentsdisciplines_controller.rb
class StudentsdisciplinesController < ApplicationController
  def create
    @student = Student.find_by(slug: params[:student_id])

  end
end

app/controllers/studentsgroups_controller.rb
class StudentsgroupsController < ApplicationController
  def new
    @discipline = Discipline.find(params[:discipline_id])
    @student = Student.find(params[:student_id])
    if @discipline.individual?
      @students = Student.all
      @group = @student.groups.new(name: @student.last_name, discipline: @discipline,
                 variant: @discipline.variant)
      @studentsgroup = @student.studentsgroups.new
      render "groups/new"
      # @group.students << @student
    # else

    end
  end

 def create
   binding.pry
 end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
  end

  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    @teacher.update(teacher_params)
    redirect_to @teacher
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.save
    redirect_to @teacher
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    redirect_to teachers_url
  end

private
  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :age, :experience, :speciality)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(text, url)
    classes = ['button']
    classes << 'active' if current_page?(url)
    link_to(text, url, class: classes.join(' '))
  end

  def top_nav_link_to(text, url)
    if current_page?(url)
      content_tag(:li, link_to(text, url), class: 'active')
    else
      content_tag(:li, link_to(text, url))
    end
  end

  def glyph(*names)
    content_tag :i, nil, class: names.map{|name| "glyphicon glyphicon-#{name.to_s.gsub('_','-')}" }
  end

  def dropdown_caret
    content_tag :b, nil, class: "caret"
  end

  # def dropdown_caret_link_to(text,url)
  #   link_to(url, data: { toggle: "dropdown"}, class: "dropdown-toggle") do
  #     "#{text}" content_tag(:b, class: "caret")
  #   end
  # end

end

app/helpers/disciplines_helper.rb
module DisciplinesHelper

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studentsdisciplines_helper.rb
module StudentsdisciplinesHelper
end

app/helpers/studentsgroups_helper.rb
module StudentsgroupsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/disciplines/_form.html.erb
<%= form_for @discipline, html: { class: "form-horizontal", role: "form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Pavadinimas', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :speciality, 'Specialybė', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.select :speciality, Discipline::SPECIALITIES, {}, {class: "form-control"} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :klass, 'Klasė', class: "col-sm-4 control-label" %>
    <div class="col-sm-3">
      <%= f.select :klass, Discipline::KLASSES, {}, { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :duration, 'Valandų', class: "col-sm-4 control-label" %>
    <div class="col-sm-3">
      <%= f.number_field :duration, { step: "0.5", class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :syllabus, 'Programa', class: "col-sm-4 control-label" %><rb />
    <div class="col-sm-8">
    <% Discipline::SYLLABUS.each do |syllabus| %>
      <div class="radio">
        <%= f.radio_button :syllabus, syllabus %> <%= syllabus %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :variant, 'Forma', class: "col-sm-4 control-label" %><rb />
    <div class="col-sm-8">
    <% Discipline::VARIANTS.each do |variant| %>
      <div class="radio">
        <%= f.radio_button :variant, variant %> <%= variant %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :required, 'Privaloma?', class: "col-sm-4 control-label" %><rb />
    <div class="col-sm-8">
    <% if @discipline.new_record? %>
      <div class="radio">
        <%= f.radio_button :required, false %> Ne
      </div>
    <% else %>
      <div class="radio-inline">
        <%= f.radio_button :required, true %> Taip
      </div>
      <div class="radio-inline">
        <%= f.radio_button :required, false %> Ne
      </div>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, 'Būsena?', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <% if @discipline.new_record? %>
      <div class="radio">
        <%= f.radio_button :status, false %> Neaktyvi
      </div>
    <% else %>
      <div class="radio-inline">
        <%= f.radio_button :status, true %> Aktyvi
      </div>
      <div class="radio-inline">
        <%= f.radio_button :status, false %> Neaktyvi
      </div>
    <% end %>
    </div>
  </div>

    <div class="form-group margintopmid">
      <div class="col-sm-offset-4 col-sm-8">
        <%= f.submit class: "btn btn-primary" %> <%= link_to "Cancel", disciplines_path, class: "btn btn-warning" %>
      </div>
    </div>
<% end %>

app/views/disciplines/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
      <h1>Editing discipline:</h1>
    </div>
      <%= render 'form' %>
  </div>
</div>

app/views/disciplines/index.html.erb
<div class="row">
  <div class="page-header">
  <div class="row">
    <div class="col-sm-9">
      <h1>Disciplines</h1>
    </div>
    <div class="col-sm-3">
      <div class="pull-right discipline_new">
        <%= link_to 'New', new_discipline_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  </div>
</div>


<div class="table-responsive">
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>Pavadinimas</th>
      <th>Spacialibė</th>
      <th>Kl.</th>
      <th>Val.</th>
      <th>Programa</th>
      <th>Forma</th>
      <th>Privalomas</th>
      <th>Būsena</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @disciplines.each do |discipline| %>
    <tr>
      <td><%= discipline.name %></td>
      <td><%= discipline.speciality %></td>
      <td><%= discipline.klass %></td>
      <td><%= discipline.duration %></td>
      <td><%= discipline.syllabus %></td>
      <td><%= discipline.variant %></td>

      <td><%= discipline.is_required? %></td>
      <td><%= discipline.what_status? %></td>
      <td><%= link_to glyph(:pencil) + ' Edit', edit_discipline_path(discipline) %>
       <%= link_to glyph(:trash) + ' Delete', discipline, method: :delete,
                data: { confirm: "Are you sore?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/disciplines/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
      <h1>Creating discipline:</h1>
    </div>
      <%= render 'form' %>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_for @group, html: { class: "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :variant, 'Forma', class: "col-sm-4 control-label" %><rb />
    <div class="col-sm-8">
    <% Discipline::VARIANTS.each do |variant| %>
      <div class="radio">
        <%= f.radio_button :variant, variant %> <%= variant %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :discipline_id, 'Discipline', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.select :discipline_id, Discipline.all.collect {|d| [ "#{d.name} #{d.klass} kl.", d.id ] }, {}, { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :teacher_id, 'Teacher', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.select :teacher_id, Teacher.all.collect {|t| [ "#{t.first_name} #{t.last_name}",
     t.id ] }, {}, { class: "form-control" } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Pastabos', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.text_area :description, cols: 80, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :studentsgroups, 'Student', class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
    <%= f.select :studentsgroups, Student.all.collect {|t| [ "#{t.first_name} #{t.last_name}",
     t.id ] }, {}, { class: "form-control" } %>
    </div>
  </div>

  <%= f.fields_for :students do |builder| %>
    <fieldset>
      <%= builder.label :student_id, "Students" %><br/>
      <%= builder.select :student_id, Student.all.collect {|t| [ "#{t.first_name} #{t.last_name}",
     t.id ] }, {}, { class: "form-control" } %>
    </fieldset>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", groups_path, class: "btn btn-warning" %>
    </div>
  </div>

<% end %>

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h1>Editing group:</h1>
    </div>
      <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="page-header">
  <div class="row">
    <div class="col-sm-9">
      <h1>Groups</h1>
    </div>
    <div class="col-sm-3">
      <div class="pull-right discipline_new">
        <%= link_to 'New', new_group_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  </div>
</div>


<div class="table-responsive">
<table class="table table-striped table-hover table-bordered">
<thead>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Teacher</th>
    <th>Discipline</th>
    <th>Klass</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
  <% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= group.variant %></td>
    <td><%= group.teacher.first_name %> <%= group.teacher.last_name %></td>
    <td><%= group.discipline.name %></td>
    <td><%= group.discipline.klass %></td>
    <td><%= link_to glyph(:pencil) + ' Edit', edit_group_path(group) %>
     <%= link_to glyph(:trash) + ' Delete', group, method: :delete,
              data: { confirm: "Are you sore?" } %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h1>Creating group:</h1>
    </div>
      <%= render 'groups/form' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
      <div class="container">
        <p class="text-muted">Daybook for schools, by <a href="https://www.manoevis.com/">
          Evaldas Grudzinskas</a>. &copy; 2014</p>
      </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">El. dienynas</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mokiniai <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Visi', students_path %></li>
            <li><%= link_to 'Sukurti naują', new_student_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mokytojai <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Visi', teachers_path %></li>
            <li><%= link_to 'Sukurti naują', new_teacher_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ugdymo planas <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Disciplinos', disciplines_path %></li>
            <li><%= link_to 'Sukurti Discipliną', new_discipline_path %></li>
            <li></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Grupės <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Visos', groups_path %></li>
            <li><%= link_to 'Sukurti grupę', new_group_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Žurnalai <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li></li>
            <li></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h1>Editing student:</h1>
    </div>
      <%= render 'form' %>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="page-header">
  <div class="row">
    <div class="col-sm-9">
      <h1>Students</h1>
    </div>
    <div class="col-sm-3">
      <div class="pull-right discipline_new">
        <%= link_to 'New', new_student_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  </div>
</div>


<div class="table-responsive">
<table class="table table-striped table-hover table-bordered">
<thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Class</th>
    <th>Speciality</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
  <% @students.each do |student| %>
  <tr>
    <td><%= student.first_name %></td>
    <td><%= link_to student.last_name, student %></td>
    <td><%= student.klass %></td>
    <td><%= student.speciality %></td>
    <td><%= link_to glyph(:pencil) + ' Edit profile', edit_student_path(student) %>
     <%= link_to glyph(:trash) + ' Delete', student, method: :delete,
              data: { confirm: "Are you sore?" } %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
    <h1><%= @student.first_name %> <%= @student.last_name %></h1>
    </div>
    <table class="table table-bordered">
    <tr>
      <th>Age</th>
      <td><%= @student.age %></td>
    </tr>
    <tr>
      <th>Class</th>
      <td><%= @student.klass %></td>
    </tr>
    <tr>
      <th>Spaciality</th>
      <td><%= @student.speciality %></td>
    </tr>
    </table>
  </div>
  <div class="col-md-3 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">Valdymas</div>
        <ul class="nav nav-pills nav-stacked">
          <%= top_nav_link_to 'Edit', edit_student_path(@student) %>
          <li><%= link_to 'Delete', @student, method: :delete,
              data: { confirm: "Are you sore?" } %></li>
          <%= top_nav_link_to 'Visi mokiniai', students_path %>
        </ul>
    </div>
    <% if @student.studentsdisciplines.active_only.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">Priskirti mokytojus!</div>
        <ul class="nav nav-pills nav-stacked">
        <% @student.studentsdisciplines.active_only.each do |sd| %>
            <li><%= link_to sd.discipline.name, new_student_studentsgroup_path(student_id: @student.id, discipline_id: sd.discipline.id) %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
  </div>
</div>

app/views/studentsgroups/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="page-header">
      <h1>Creating group:</h1>
    </div>


      <%= form_for @group, html: { class: "form-horizontal", role: "form" } do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :variant, 'Forma', class: "col-sm-4 control-label" %><rb />
          <div class="col-sm-8">
          <% Discipline::VARIANTS.each do |variant| %>
            <div class="radio">
              <%= f.radio_button :variant, variant %> <%= variant %>
            </div>
          <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :discipline_id, 'Discipline', class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
          <%= f.select :discipline_id, Discipline.all.collect {|d| [ "#{d.name} #{d.klass} kl.", d.id ] }, {}, { class: "form-control" } %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :teacher_id, 'Teacher', class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
          <%= f.select :teacher_id, Teacher.all.collect {|t| [ "#{t.first_name} #{t.last_name}",
           t.id ] }, {}, { class: "form-control" } %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, 'Pastabos', class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
          <%= f.text_area :description, cols: 80, class: "form-control" %>
          </div>
        </div>

        <%= f.fields_for :students do |builder| %>
          <fieldset>
            <%= builder.label :student_id, "Students" %><br/>
            <%= builder.select :student_id, Student.all.collect {|t| [ "#{t.first_name} #{t.last_name}",
           t.id ] }, {}, { class: "form-control" } %>
          </fieldset>
        <% end %>
        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-8">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", students_path, class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>

  </div>
</div>

app/views/teachers/index.html.erb
<div class="row">
  <div class="page-header">
  <div class="row">
    <div class="col-sm-9">
      <h1>Teachers</h1>
    </div>
    <div class="col-sm-3">
      <div class="pull-right discipline_new">
        <%= link_to 'New', new_teacher_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
  </div>
</div>


<div class="table-responsive">
<table class="table table-striped table-hover table-bordered">
<thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Speciality</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
  <% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.first_name %></td>
    <td><%= link_to teacher.last_name, teacher %></td>
    <td><%= teacher.speciality %></td>
    <td><%= link_to glyph(:pencil) + ' Edit profile', edit_teacher_path(teacher) %>
     <%= link_to glyph(:trash) + ' Delete', teacher, method: :delete,
              data: { confirm: "Are you sore?" } %></td>
  </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/teachers/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
    <h1><%= @teacher.first_name %> <%= @teacher.last_name %></h1>
    </div>
    <table class="table table-bordered">
    <tr>
      <th>Age</th>
      <td><%= @teacher.age %></td>
    </tr>
    <tr>
      <th>Experience</th>
      <td><%= @teacher.experience %></td>
    </tr>
    <tr>
      <th>Spaciality</th>
      <td><%= @teacher.speciality %></td>
    </tr>
    </table>
  </div>
  <div class="col-md-3 col-md-offset-5">
    <div class="panel panel-primary">
      <div class="panel-heading">Valdymas</div>
        <ul class="nav nav-pills nav-stacked">
          <%= top_nav_link_to 'Edit', edit_teacher_path(@teacher) %>
          <li><%= link_to 'Delete', @teacher, method: :delete,
              data: { confirm: "Are you sore?" } %></li>
          <%= top_nav_link_to 'Visi mokytojai', teachers_path %>
        </ul>
    </div>
  </div>
</div>